### PR TITLE
Improve translation

### PR DESCRIPTION
**Pull request by NathanBnm**
I removed untranslated files to avoid confusion. I also split the metadata translation from the main one.

**This PR is ready for review**

### CODE REVIEW

**Comment by cassidyjames** [comment]
@NathanBnm thanks for this! I have mixed thoughts on the untranslated files; I think I need to update the translation README if we drop those to tell people how to add their own language. I'll ask around how other app authors feel about that.

Could you please fix conflicts?

**Comment by NathanBnm** [comment]
Sure I'll do that.

I think it's better to only keep available translations because when a language is not available, we can notice it immediatly.

I'ts more clear too to separate the metadata translations from the main ones.

I can work around it if you want. I already seen it in other repos.

**Comment by NathanBnm** [comment]
I have resolved the conflicts and updated French translation.

**Comment by NathanBnm** [comment]
@cassidyjames maybe you could take example on @lainsce like here https://github.com/lainsce/khronos/tree/master/po

However, I think further instruction is needed on how to create a PR

**Comment by fitojb** [comment]
Isn’t it better to create focused PRs and not include drive-bys like updating translated strings?

**Comment by fitojb** [comment]
(IMHO)

**Comment by NathanBnm** [comment]
@fitojb you're right. I'll think about it for my future PRs.

**Pull request merged**
