### PR TITLE
Open url in default browser (#1)

### PR DESCRIPTION
**Pull request by pablopunk**
I thought opening in default browser would be a good idea :)

### CODE REVIEW

**Comment by cassidyjames** [comment]
@pablopunk so that's the intent of #1, but the problem with "default" is that the idea is you can set Ephemeral as your default browser. In that case, it wouldn't make sense to show the default app there. However, I think as part of #1 I'm going to want to keep track of the last-used browser internally and use that by default.

**Comment by cassidyjames** [comment]
@pablopunk however, I may merge this as-is for now and figure out the last-used behavior if Ephemeral is the default later. :smile: Thanks for the PR!

**Comment by pablopunk** [comment]
Thanks! Yeah I didn’t think about that... I will probably not show the
button at all if Ephemeral is the default, to keep it simple.

**Comment by pablopunk** [comment]
Then IMO a dropdown would be easy enough. Maybe after the user selects a
browser keep that as the default option

**Pull request merged**
