### PR TITLE
Provide Spanish translation

### PR DESCRIPTION
**Pull request by fitojb**
Apologies for opening the same PR twice, but I messed up my rebasing lol

### CODE REVIEW

**Comment by felix91gr** [comment]
Question for you @fitojb: I wanted to provide a Spanish translation as well, and my idea of what voice to use is different from what you used. Lemme put it in spanish:

For "Search the web",

Your translation looked like this:
> Explore la web

Mine would've looked like this:
> Explora la web

It's a different voice, or distance from the user maybe. I'm chilean, so maybe I'm used to the second way of expression. Is there's space for both? Maybe having two localizations is better: `es-es ` for "España" and `es-lat` for "Latinoamérica".

The other option could be to replicate the default voice used in Elementary's Spanish translations, and make it consistent across the system :)

**Comment by fitojb** [comment]
The [right](https://wiki.gnome.org/TranslationProject/SpanishTeam?action=AttachFile&do=view&target=GNOME_l10n_es.pdf) voice [is](https://wiki.documentfoundation.org/ES/Gu%C3%ADa_de_estilo#Estilo) the [formal](https://wiki.ubuntu.com/UbuntuSpanishTranslators/Estilo#Registro) one, and that is independent of locale. Please do not start forking away localization efforts just because you don’t like it. Using the informal voice means that you also have to create and MAINTAIN a third localization for the Argentine _vos_-conjugation, and a couple more for the slightly different _vos_-conjugations of Paraguay and Uruguay, effectively quadrupling the effort. Just say no. _Usted_ works everywhere.

**Comment by felix91gr** [comment]
Hey hey, it's okay man. I'm just asking :)

I have no idea about this, it just feels strange to have a program treat me like a god or something. Remember that we _do_ have important cultural differences in what our default distance to other people is. 

Besides, there's a precedent in `fr` and `fr_CA` and `en`, `en_GB`, `en_US`, `en_AU`, etc.

**Comment by fitojb** [comment]
Hm, since when has it become so controversial to use _usted_? I’ve been using Windows since 3.1 and it’s always treated users with the formal voice.<sup>[1]</sup> Also, before Android came about and flooded the market with cheaply done translations, mobile phones treated people formally (I still have my Sony Ericsson W508 with me… I’ve never felt it’s treated me like a god!)

> Besides, there's a precedent in `fr` and `fr_CA` and `en`, `en_GB`, `en_US`, `en_AU`, etc.

This is a straw man: both Canadian and general French locales use the formal _vous_ treatment and are just there to address differences in lexicon, so that’s not relevant for this issue.

----
[1]: (It was only in Windows 10 when they have changed to _tú_ (half-assedly and based on a false notion of “friendly language” that came from California, assuming that all users are teenagers… I digress.)

**Comment by felix91gr** [comment]
Ah, I see. Okay, I think I get your point now: localization and voicing should be kept separate.

Still, the formal voicing makes me a bit uncomfortable. Maybe that's why I end up changing to English in my OSes most of the time. Well. Maybe one day we'll have a way to dynamically adjust the formality of dialog without having to maintain 2 locale files for each lexicon.

Thanks for the responses. Have a good week!

**Pull request merged**
